/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as ContractorJobsRouteImport } from './routes/contractor-jobs'
import { Route as ContractorsRouteImport } from './routes/contractors'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as InspectionRouteImport } from './routes/inspection'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as StatusRouteImport } from './routes/status'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PartnerAnalyticsRouteImport } from './routes/partner.analytics'
import { Route as PartnerCasesRouteImport } from './routes/partner.cases'
import { Route as PartnerInspectionsRouteImport } from './routes/partner.inspections'
import { Route as PartnerOpportunitiesRouteImport } from './routes/partner.opportunities'
import { Route as PartnerOverflowRouteImport } from './routes/partner.overflow'
import { Route as PartnerProgramsRouteImport } from './routes/partner.programs'
import { Route as PartnerUnmetNeedsRouteImport } from './routes/partner.unmet-needs'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'
import { Route as PartnerCasesIndexRouteImport } from './routes/partner.cases.index'
import { Route as PartnerCasesCaseIdRouteImport } from './routes/partner.cases.$caseId'
import { Route as PartnerOverflowIndexRouteImport } from './routes/partner.overflow.index'
import { Route as PartnerOverflowJobIdRouteImport } from './routes/partner.overflow.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorJobsRoute = ContractorJobsRouteImport.update({
  id: '/contractor-jobs',
  path: '/contractor-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsRoute = ContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRoute = InspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerAnalyticsRoute = PartnerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerCasesRoute = PartnerCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerInspectionsRoute = PartnerInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerOpportunitiesRoute = PartnerOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerOverflowRoute = PartnerOverflowRouteImport.update({
  id: '/overflow',
  path: '/overflow',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerProgramsRoute = PartnerProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerUnmetNeedsRoute = PartnerUnmetNeedsRouteImport.update({
  id: '/unmet-needs',
  path: '/unmet-needs',
  getParentRoute: () => PartnerRoute,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerCasesIndexRoute = PartnerCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerCasesRoute,
} as any)
const PartnerCasesCaseIdRoute = PartnerCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => PartnerCasesRoute,
} as any)
const PartnerOverflowIndexRoute = PartnerOverflowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerOverflowRoute,
} as any)
const PartnerOverflowJobIdRoute = PartnerOverflowJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => PartnerOverflowRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/contractor-jobs': typeof ContractorJobsRoute
  '/contractors': typeof ContractorsRoute
  '/coverage': typeof CoverageRoute
  '/inspection': typeof InspectionRoute
  '/intake': typeof IntakeRoute
  '/partner': typeof PartnerRouteWithChildren
  '/passport': typeof PassportRoute
  '/status': typeof StatusRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/cases': typeof PartnerCasesRouteWithChildren
  '/partner/inspections': typeof PartnerInspectionsRoute
  '/partner/opportunities': typeof PartnerOpportunitiesRoute
  '/partner/overflow': typeof PartnerOverflowRouteWithChildren
  '/partner/programs': typeof PartnerProgramsRoute
  '/partner/unmet-needs': typeof PartnerUnmetNeedsRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/partner/': typeof PartnerIndexRoute
  '/partner/cases/$caseId': typeof PartnerCasesCaseIdRoute
  '/partner/overflow/$jobId': typeof PartnerOverflowJobIdRoute
  '/partner/cases/': typeof PartnerCasesIndexRoute
  '/partner/overflow/': typeof PartnerOverflowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/contractor-jobs': typeof ContractorJobsRoute
  '/contractors': typeof ContractorsRoute
  '/coverage': typeof CoverageRoute
  '/inspection': typeof InspectionRoute
  '/intake': typeof IntakeRoute
  '/passport': typeof PassportRoute
  '/status': typeof StatusRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/inspections': typeof PartnerInspectionsRoute
  '/partner/opportunities': typeof PartnerOpportunitiesRoute
  '/partner/programs': typeof PartnerProgramsRoute
  '/partner/unmet-needs': typeof PartnerUnmetNeedsRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/partner': typeof PartnerIndexRoute
  '/partner/cases/$caseId': typeof PartnerCasesCaseIdRoute
  '/partner/overflow/$jobId': typeof PartnerOverflowJobIdRoute
  '/partner/cases': typeof PartnerCasesIndexRoute
  '/partner/overflow': typeof PartnerOverflowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/contractor-jobs': typeof ContractorJobsRoute
  '/contractors': typeof ContractorsRoute
  '/coverage': typeof CoverageRoute
  '/inspection': typeof InspectionRoute
  '/intake': typeof IntakeRoute
  '/partner': typeof PartnerRouteWithChildren
  '/passport': typeof PassportRoute
  '/status': typeof StatusRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/cases': typeof PartnerCasesRouteWithChildren
  '/partner/inspections': typeof PartnerInspectionsRoute
  '/partner/opportunities': typeof PartnerOpportunitiesRoute
  '/partner/overflow': typeof PartnerOverflowRouteWithChildren
  '/partner/programs': typeof PartnerProgramsRoute
  '/partner/unmet-needs': typeof PartnerUnmetNeedsRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/partner/': typeof PartnerIndexRoute
  '/partner/cases/$caseId': typeof PartnerCasesCaseIdRoute
  '/partner/overflow/$jobId': typeof PartnerOverflowJobIdRoute
  '/partner/cases/': typeof PartnerCasesIndexRoute
  '/partner/overflow/': typeof PartnerOverflowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/contractor-jobs'
    | '/contractors'
    | '/coverage'
    | '/inspection'
    | '/intake'
    | '/partner'
    | '/passport'
    | '/status'
    | '/partner/analytics'
    | '/partner/cases'
    | '/partner/inspections'
    | '/partner/opportunities'
    | '/partner/overflow'
    | '/partner/programs'
    | '/partner/unmet-needs'
    | '/programs/$programId'
    | '/partner/'
    | '/partner/cases/$caseId'
    | '/partner/overflow/$jobId'
    | '/partner/cases/'
    | '/partner/overflow/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/contractor-jobs'
    | '/contractors'
    | '/coverage'
    | '/inspection'
    | '/intake'
    | '/passport'
    | '/status'
    | '/partner/analytics'
    | '/partner/inspections'
    | '/partner/opportunities'
    | '/partner/programs'
    | '/partner/unmet-needs'
    | '/programs/$programId'
    | '/partner'
    | '/partner/cases/$caseId'
    | '/partner/overflow/$jobId'
    | '/partner/cases'
    | '/partner/overflow'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/contractor-jobs'
    | '/contractors'
    | '/coverage'
    | '/inspection'
    | '/intake'
    | '/partner'
    | '/passport'
    | '/status'
    | '/partner/analytics'
    | '/partner/cases'
    | '/partner/inspections'
    | '/partner/opportunities'
    | '/partner/overflow'
    | '/partner/programs'
    | '/partner/unmet-needs'
    | '/programs/$programId'
    | '/partner/'
    | '/partner/cases/$caseId'
    | '/partner/overflow/$jobId'
    | '/partner/cases/'
    | '/partner/overflow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  ContractorJobsRoute: typeof ContractorJobsRoute
  ContractorsRoute: typeof ContractorsRoute
  CoverageRoute: typeof CoverageRoute
  InspectionRoute: typeof InspectionRoute
  IntakeRoute: typeof IntakeRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PassportRoute: typeof PassportRoute
  StatusRoute: typeof StatusRoute
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor-jobs': {
      id: '/contractor-jobs'
      path: '/contractor-jobs'
      fullPath: '/contractor-jobs'
      preLoaderRoute: typeof ContractorJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors': {
      id: '/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof ContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection': {
      id: '/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof InspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/analytics': {
      id: '/partner/analytics'
      path: '/analytics'
      fullPath: '/partner/analytics'
      preLoaderRoute: typeof PartnerAnalyticsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/cases': {
      id: '/partner/cases'
      path: '/cases'
      fullPath: '/partner/cases'
      preLoaderRoute: typeof PartnerCasesRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/inspections': {
      id: '/partner/inspections'
      path: '/inspections'
      fullPath: '/partner/inspections'
      preLoaderRoute: typeof PartnerInspectionsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/opportunities': {
      id: '/partner/opportunities'
      path: '/opportunities'
      fullPath: '/partner/opportunities'
      preLoaderRoute: typeof PartnerOpportunitiesRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/overflow': {
      id: '/partner/overflow'
      path: '/overflow'
      fullPath: '/partner/overflow'
      preLoaderRoute: typeof PartnerOverflowRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/programs': {
      id: '/partner/programs'
      path: '/programs'
      fullPath: '/partner/programs'
      preLoaderRoute: typeof PartnerProgramsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/unmet-needs': {
      id: '/partner/unmet-needs'
      path: '/unmet-needs'
      fullPath: '/partner/unmet-needs'
      preLoaderRoute: typeof PartnerUnmetNeedsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/cases/': {
      id: '/partner/cases/'
      path: '/'
      fullPath: '/partner/cases/'
      preLoaderRoute: typeof PartnerCasesIndexRouteImport
      parentRoute: typeof PartnerCasesRoute
    }
    '/partner/cases/$caseId': {
      id: '/partner/cases/$caseId'
      path: '/$caseId'
      fullPath: '/partner/cases/$caseId'
      preLoaderRoute: typeof PartnerCasesCaseIdRouteImport
      parentRoute: typeof PartnerCasesRoute
    }
    '/partner/overflow/': {
      id: '/partner/overflow/'
      path: '/'
      fullPath: '/partner/overflow/'
      preLoaderRoute: typeof PartnerOverflowIndexRouteImport
      parentRoute: typeof PartnerOverflowRoute
    }
    '/partner/overflow/$jobId': {
      id: '/partner/overflow/$jobId'
      path: '/$jobId'
      fullPath: '/partner/overflow/$jobId'
      preLoaderRoute: typeof PartnerOverflowJobIdRouteImport
      parentRoute: typeof PartnerOverflowRoute
    }
  }
}

interface PartnerCasesRouteChildren {
  PartnerCasesCaseIdRoute: typeof PartnerCasesCaseIdRoute
  PartnerCasesIndexRoute: typeof PartnerCasesIndexRoute
}

const PartnerCasesRouteChildren: PartnerCasesRouteChildren = {
  PartnerCasesCaseIdRoute: PartnerCasesCaseIdRoute,
  PartnerCasesIndexRoute: PartnerCasesIndexRoute,
}

const PartnerCasesRouteWithChildren = PartnerCasesRoute._addFileChildren(
  PartnerCasesRouteChildren,
)

interface PartnerOverflowRouteChildren {
  PartnerOverflowJobIdRoute: typeof PartnerOverflowJobIdRoute
  PartnerOverflowIndexRoute: typeof PartnerOverflowIndexRoute
}

const PartnerOverflowRouteChildren: PartnerOverflowRouteChildren = {
  PartnerOverflowJobIdRoute: PartnerOverflowJobIdRoute,
  PartnerOverflowIndexRoute: PartnerOverflowIndexRoute,
}

const PartnerOverflowRouteWithChildren = PartnerOverflowRoute._addFileChildren(
  PartnerOverflowRouteChildren,
)

interface PartnerRouteChildren {
  PartnerAnalyticsRoute: typeof PartnerAnalyticsRoute
  PartnerCasesRoute: typeof PartnerCasesRouteWithChildren
  PartnerInspectionsRoute: typeof PartnerInspectionsRoute
  PartnerOpportunitiesRoute: typeof PartnerOpportunitiesRoute
  PartnerOverflowRoute: typeof PartnerOverflowRouteWithChildren
  PartnerProgramsRoute: typeof PartnerProgramsRoute
  PartnerUnmetNeedsRoute: typeof PartnerUnmetNeedsRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerAnalyticsRoute: PartnerAnalyticsRoute,
  PartnerCasesRoute: PartnerCasesRouteWithChildren,
  PartnerInspectionsRoute: PartnerInspectionsRoute,
  PartnerOpportunitiesRoute: PartnerOpportunitiesRoute,
  PartnerOverflowRoute: PartnerOverflowRouteWithChildren,
  PartnerProgramsRoute: PartnerProgramsRoute,
  PartnerUnmetNeedsRoute: PartnerUnmetNeedsRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  ContractorJobsRoute: ContractorJobsRoute,
  ContractorsRoute: ContractorsRoute,
  CoverageRoute: CoverageRoute,
  InspectionRoute: InspectionRoute,
  IntakeRoute: IntakeRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PassportRoute: PassportRoute,
  StatusRoute: StatusRoute,
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
